spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://ott-mysql:3306/ottdb
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
